Papp 736 add query ordering support to specification pattern
PappDanmark/DatabaseAccess pull request #29
Opened 2022-10-05 08:58 UTC by Maxim-Zavidei

# Overview:
* [PAPP-736] Added ordering functionality to the specification pattern
* [PAPP-736] Implemented a method to retrieve lastest sensor update
* [PAPP-736] Inlcude the sensor installation with the bundle

2022-10-05 10:16 UTC, Logstor requested changes
Really nice :+1: 
Only a little documentation thingy :wink:

2022-10-05 10:16 UTC, Logstor commented on Papp.Persistence/Source/DataAccess/SensorUpdate/ISensorUpdateDataAccess.cs
> +    SensorUpdate GetLastestBySensorId(string id);
Shouldn't be a nullable type or is this turned off for this project? :slightly_smiling_face:

2022-10-05 10:16 UTC, Logstor commented on Papp.Persistence/Source/DataAccess/SensorUpdate/SensorUpdateDataAccess.cs
> +    public SensorUpdate? GetLastestBySensorId(string id)
Remember `///<inheritdoc/>` :+1:

2022-10-06 10:26 UTC, Maxim-Zavidei commented on Papp.Persistence/Source/DataAccess/SensorUpdate/ISensorUpdateDataAccess.cs
> +    SensorUpdate GetLastestBySensorId(string id);
oh yes that's correct

2022-10-06 10:29 UTC, Maxim-Zavidei commented on Papp.Persistence/Source/DataAccess/SensorUpdate/SensorUpdateDataAccess.cs
> +    public SensorUpdate? GetLastestBySensorId(string id)
good notice

2022-10-06 18:17 UTC, Logstor requested changes
One small thing, otherwise really good work :muscle:

2022-10-06 18:17 UTC, Logstor commented on Papp.Persistence/Source/DataAccess/SensorUpdate/SensorUpdateDataAccess.cs
> +            .FirstOrDefault();
Maybe also use the `take(1)` here :wink:

2022-10-07 13:10 UTC, merged